-- MySQL Script generated by MySQL Workbench
-- Thu Mar 20 13:41:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema api_docs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api_docs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api_docs` DEFAULT CHARACTER SET utf8mb4 ;
USE `api_docs` ;

-- -----------------------------------------------------
-- Table `api_docs`.`analise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_docs`.`analise` (
  `id_analise` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `link_pdf` VARCHAR(255) NULL,
  `resumo` VARCHAR(255) NULL,
  `data` DATETIME NULL,
  `usuario_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id_analise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api_docs`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_docs`.`proprietario` (
  `id_proprietario` INT(11) NOT NULL AUTO_INCREMENT,
  `analise_id` INT(11) NOT NULL,
  `nome_razao` VARCHAR(255) NULL,
  `nome_mae` VARCHAR(255) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `data_nascimento` DATETIME NULL,
  `estado_civil` VARCHAR(45) NULL,
  `e_empresa` TINYINT NULL,
  `nome_representante` VARCHAR(255) NULL,
  `nome_mae_representante` VARCHAR(255) NULL,
  `cpf_representante` VARCHAR(45) NULL,
  `data_nascimento_representante` DATETIME NULL,
  `pdf_sefaz` VARCHAR(255) NULL,
  `pdf_trabalho` VARCHAR(255) NULL,
  `pdf_nada_consta_civel` VARCHAR(255) NULL,
  `pdf_nada_consta_criminal` VARCHAR(255) NULL,
  `pdf_nada_consta_falencia` VARCHAR(255) NULL,
  `pdf_nada_consta_especial` VARCHAR(255) NULL,
  `pdf_receita` VARCHAR(255) NULL,
  `pdf_tjdf_criminal` VARCHAR(255) NULL,
  `pdf_tjdf_eleitoral` VARCHAR(255) NULL,
  `pdf_tjdf_civel` VARCHAR(255) NULL,
  `ad` VARCHAR(255) NULL,
  PRIMARY KEY (`id_proprietario`),
  INDEX `fk_proprietario_analise` (`analise_id` ASC),
  CONSTRAINT `fk_proprietario_analise`
    FOREIGN KEY (`analise_id`)
    REFERENCES `api_docs`.`analise` (`id_analise`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api_docs`.`esposa_socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_docs`.`esposa_socio` (
  `id_esposa_socio` INT(11) NOT NULL AUTO_INCREMENT,
  `proprietario_id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NULL,
  `cpf` VARCHAR(45) NULL,
  `data_nascimento` DATETIME NULL,
  `nome_mae` VARCHAR(255) NULL,
  `pdf_sefaz` VARCHAR(255) NULL,
  `pdf_trabalho` VARCHAR(255) NULL,
  `pdf_nada_consta_civel` VARCHAR(255) NULL,
  `pdf_nada_consta_criminal` VARCHAR(255) NULL,
  `pdf_nada_consta_falencia` VARCHAR(255) NULL,
  `pdf_nada_consta_especial` VARCHAR(255) NULL,
  `pdf_receita` VARCHAR(255) NULL,
  `pdf_tjdf_criminal` VARCHAR(255) NULL,
  `pdf_tjdf_eleitoral` VARCHAR(255) NULL,
  `pdf_tjdf_civel` VARCHAR(255) NULL,
  `ad` VARCHAR(255) NULL,
  PRIMARY KEY (`id_esposa_socio`),
  UNIQUE INDEX `unique_proprietario` (`proprietario_id` ASC),
  CONSTRAINT `fk_esposa_socio_proprietario`
    FOREIGN KEY (`proprietario_id`)
    REFERENCES `api_docs`.`proprietario` (`id_proprietario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api_docs`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_docs`.`imovel` (
  `id_imovel` INT(11) NOT NULL AUTO_INCREMENT,
  `analise_id` INT(11) NOT NULL,
  `cep` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  `inscricao_iptu` VARCHAR(45) NULL,
  `cartorio` VARCHAR(45) NULL,
  `matricula` VARCHAR(45) NULL,
  `pdf_sefaz` VARCHAR(45) NULL,
  PRIMARY KEY (`id_imovel`),
  UNIQUE INDEX `unique_analise_imovel` (`analise_id` ASC),
  CONSTRAINT `fk_imovel_analise`
    FOREIGN KEY (`analise_id`)
    REFERENCES `api_docs`.`analise` (`id_analise`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
